install.packages("sf")
install.packages("ggspatial")
install.packages("janitor")
install.packages("kableExtra")
install.packages("leaflet")
install.packages("mapview")
install.packages("MMWRweek")
install.packages("rnaturalearth")
install.packages("pacman")
install.packages("rgeos")
install.packages("ggrepel")
install.packages("ggnewscale")
install.packages("gtools")
install.packages("reactR")
install.packages("reactable")
install.packages("zoo")
install.packages("tidyverse")
# july 27
install.packages("knitr")
install.packages("pander")
install.packages("formattable")
install.packages("webshot")
install.packages("htmltools")
install.packages("magick")
install.packages("see")
install.packages("viridis")
install.packages("visdat")
# Shinyapp
install.packages('shinyjs')
install.packages('officer')
install.packages('flextable')
install.packages('plotly')
install.packages('devtools')
install.packages('remotes')
install.packages('RPostgreSQL')




